config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories

	validates :title, presence: true, length: {minimum: 3, maximum: 50 }
	validates :description, presence: true, length: {minimum: 3, maximum: 10000 }
	validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

	belongs_to :article
	belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories
	has_many :articles, through: :article_categories

	validates :name, presence: true, length: {minimum: 3, maximum: 25 }
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy

	before_save { self.email = email.downcase }

	validates 	:username,
				presence: true,
				uniqueness: {case_sensitive: false},
				length: {minimum: 3, maximum: 15}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates 	:email,
				presence: true,
				uniqueness: {case_sensitive: false},
				length: {maximum: 105},
				format: { with: VALID_EMAIL_REGEX }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_back(fallback_location: root_path)
		end
	end

	def require_same_user(user)
		if current_user != user && !current_user.admin?
			flash[:danger] = "You can't do that"
			redirect_back(fallback_location: root_path)
		end
	end

	def require_admin
		if !logged_in? || (logged_in? && !current_user.admin?)
			flash[:warning] = "Requires Admin Privileges"
			redirect_back(fallback_location: root_path)
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :show, :update, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action only: [:edit, :update, :destroy] do
	  require_same_user(@article.user)
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article saved"
			redirect_to article_path(@article)
		else
			render :new
		end
	end

	def show
		set_article
	end

	def edit
		set_article
	end

	def update
		set_article

		if @article.update(article_params)
			flash[:warning] = "Article updated"
			redirect_to article_path(@article)
		else
			render :edit
		end
	end

	def destroy
		set_article
		@article.destroy
		flash[:danger] = "Article deleted"
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]


	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category created successfully"
			redirect_to categories_path
		else
			render :new
		end
	end

	def edit
		set_category
	end

	def update
		set_category
		if @category.update(category_params)
			flash[:succes] = "Category updated"
			redirect_to category_path(@category)
		else
			render :edit
		end
	end

	def show
		set_category
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	private
	def category_params
		params.require(:category).permit(:name)
	end

	def set_category
		@category = Category.find(params[:id])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "The credentials provided were not valid"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have successfully logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :show, :update]
	before_action :require_user, except: [:new, :index, :show, :create]
	before_action only: [:edit, :update, :destroy] do
	  require_same_user(@user)
	end
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the blog #{@user.username}!"
			redirect_to user_path(@user)
		else
			render :new
		end
	end

	def edit
		set_user
	end

	def update
		set_user

		if @user.update(user_params)
			flash[:warning] = "User credentials updated"
			redirect_to articles_path
		else
			render :edit
		end
	end

	def show
		set_user
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		set_user
		@user.destroy
		flash[:danger] = "User and all articles have been deleted"
		redirect_to root_path
	end

	private
	def user_params
		params.require(:user).permit(:email, :username, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80 } )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<div class="row">
	<div class="col-xs-6 col-xs-offset-3">
		<% obj.each do |article| %>
			<div class="well well-lg">
				<div class="container-article">
					<div class="container-article-body">
						<div class="container-article-body-text">
							<%= link_to article.title, article_path(article) %>
							&nbsp;
							<%= truncate(article.description, length: 40) %>
						</div>
						<div class="container-article-body-details">
							<small> Author: <%= article.user.username if article.user %> | Created: <%= time_ago_in_words(article.created_at).gsub('about','') %> ago | Updated: <%= time_ago_in_words(article.updated_at).gsub('about','') %> ago </small>
						</div>
						<% if article.categories.any? %>
							<div class="container-article-body-categories">
								<small>
									Categories: <%= render article.categories %>
								</small>
							</div>
						<% end %>
					</div>
					<% if logged_in? && (current_user == article.user || current_user.admin?) %>
						<div class="container-article-btns">
							<%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
							&nbsp;
							<%= link_to "Delete", article_path(article), method: :delete,
								data: { confirm: "Are you sure you want to delete this article?"},
								class: "btn btn-xs btn-danger" %>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
				<%= f.label :title %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :title, class: "form-control", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :description %>
				</div>
				<div class="col-sm-8">
					<%= f.text_area :description, rows: 10, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
						<%= cb.label(class: "checkbox-inline input-checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
					<% end %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: 'btn btn-primary' %>
				<%= link_to "Cancel", articles_path, class: "btn btn-default" %>
				<% if @article.persisted? %>
					<%= link_to "All", articles_path, class: "btn btn-success" %>
				<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/articles/edit.html.erb
<div class="container">
<h1 align="center">Edit Article</h1>

<%= render 'form' %>

</div>

app/views/articles/index.html.erb
<div class="container">
	<h1 align="center">All Articles</h1>
	<%= render 'article', obj: @articles %>
	<%= render 'shared/pagination', obj: @articles %>
</div>

app/views/articles/new.html.erb
<div class="container">
	<h1 align="center">New Article</h1>

	<%= render 'form' %>

</div>

app/views/articles/show.html.erb
<div class="container">

<h2 align="center"><%= @article.title %></h2>
<div class="row">
	<div class="well col-xs-8 col-xs-offset-2">
		<h4><strong>Description:</strong></h4>
		<%= simple_format(@article.description) %>
		<hr>
		<% if @article.categories.any? %>
			<p>Categories: <%= render @article.categories %></p>
		<% end %>
		<hr>
		<div class="article-actions">
			<%= link_to "All", articles_path, class: "btn btn-xs btn-success" %>
			<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
				<%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-warning" %>
				<%= link_to "Delete", article_path(@article), method: :delete,
					data: { confirm: "Are you sure you want to delete this article?"},
					class: "btn btn-xs btn-danger" %>
			<% end %>
		</div>
	</div>
</div>

<div>
	<h3 align="center">Author:</h3>
	<%= render 'users/user', obj: [@article.user] %>
</div>

</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>&nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
				<%= f.label :name %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :name, class: "form-control", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: 'btn btn-primary' %>
				<%= link_to "Cancel", categories_path, class: "btn btn-default" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/categories/edit.html.erb
<div class="container">
	<h1 align="center">Edit Category</h1>
	<%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
	<h1 align="center">All Categories</h1>

	<% @categories.each do |category| %>

	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<div class="well well-lg">
				<div class="container-category">
					<div class="container-category-name">
						<%= link_to "#{category.name}", category_path(category) %>
					</div>
					<div class="container-category-details">
						<small><%= pluralize(category.articles.count, "article") %></small>
					</div>
				</div>
			</div>
		</div>
	</div>

	<% end %>

	<%= render 'shared/pagination', obj: @categories %>
</div>

app/views/categories/new.html.erb
<div class="container">
	<h1 align="center">Create New Category</h1>

	<%= render 'form' %>

</div>

app/views/categories/show.html.erb
<div class="container">
	<h1 align="center"><%= @category.name + " Category" %></h1>
	<% if logged_in? && current_user.admin? %>
	<div align="center" class="category-edit">
		<%= link_to "Edit Name", edit_category_path(@category), class: "btn btn-primary center" %>
	</div>
	<% end %>
	<%= render 'articles/article', obj: @category.articles %>
	<%= render 'shared/pagination', obj: @category_articles %>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">×</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to "Articles", articles_path %></li>
						<li><%= link_to "Users", users_path %></li>
						<li class="dropdown">
							<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" >
								Categories
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "All Categories", categories_path %></li>
								<li role="separator" class="divider"></li>
								<% Category.all.each do |category| %>
								<li><%= link_to "#{category.name}", category_path(category) %></li>
								<% end %>
								<% if logged_in? && current_user.admin? %>
									<li role="separator" class="divider"></li>
									<li><%= link_to "Create Category", new_category_path %></li>
								<% end %>
							</ul>
						</li>
						<% if logged_in? %>
						<li><%= link_to "New", new_article_path %></li>
						<% end %>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if logged_in? %>
							<li class="dropdown">
								<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" >
									<%= current_user.admin? ? "Admin" : current_user.username %>
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li><%= link_to "Edit", edit_user_path(current_user) %></li>
									<li><%= link_to "Show", user_path(current_user) %></li>
									<li><%= link_to "Log Out", logout_path, method: :delete %></li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to "Sign Up", signup_path %></li>
							<li><%= link_to "Log In", login_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' if !current_page?(root_path)%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">

<h1>About This Site</h1>

<%= link_to "Home Page", root_path %>

</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
  	<%= render 'layouts/messages' %>
    <h1>ALPHA BLOG</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras id enim sit amet dui rhoncus euismod. Nam at facilisis nibh, in bibendum leo. Donec massa diam, consectetur nec elit sit amet, varius venenatis tortor. Integer egestas libero quis lectus dictum, vitae laoreet justo congue.</p>
   	<%= link_to "Sign Up", signup_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/shared/_pagination.html.erb
<div align="center">
	<%= will_paginate obj %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
	<div class='col-xs-12'>
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :email %>
				</div>
				<div class="col-sm-8">
					<%= f.email_field :email, class: "form-control", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
				<%= f.label :username %>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :username, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :password %>
				</div>
				<div class="col-sm-8">
					<%= f.password_field :password, class: "form-control" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit(@user.new_record? ? "Sign Up" : "Update", class: 'btn btn-primary') %>
				<%= link_to "Cancel", root_path, class: "btn btn-default" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/_user.html.erb
<% obj.each do |user| %>
	<div class="row">
		<div class="well col-xs-8 col-xs-offset-2">
			<div class="container-user">
				<% if user %>
				<div class="container-user-img">
					<%= link_to gravatar_for(user), user_path(user) %>
				</div>
				<div class="container-user-body">
					<div class="container-user-body-username">
						<%= link_to user.username, user_path(user) %>
					</div>
					<div class="ontainer-user-body-details">
						<small><%= pluralize(user.articles.count, "article") if user.articles %></small>
					</div>
				</div>
				<div class="container-user-btns">
					<% if logged_in? && current_user.admin? %>
					<%= link_to "Delete", user_path(user), method: :delete,
						data: { confirm: "Are you sure you want to delete this user and their articles?"},
						class: "btn btn-xs btn-danger" %>
					<% end %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">

	<h1 align="center">Edit User</h1>

	<%= render 'form' %>

</div>

app/views/users/index.html.erb
<div class="container">
	<h1 align="center">All Users</h1>
	<%= render 'user', obj: @users %>
	<%= render'shared/pagination', obj: @users %>
</div>

app/views/users/new.html.erb
<div class="container">

	<h1 align="center">Create New User</h1>

	<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="container">

	<h1 align="center">Welcome to <%= @user.username %>'s page! </h1>
	<div class="row">
		<div class="col-md-4 col-md-offset-4" align="center">
			<%= gravatar_for @user, size: 150 %>
		</div>
	</div>
	<h4 align="center"><%= @user.username %>'s Articles:</h4>
	<%= render 'articles/article', obj: @user.articles %>

	<%= render 'shared/pagination', obj: @user_articles %>

</div>